alias cd..='cd ..'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias .2='cd ../..'
alias .3='cd ../../..'
alias .4='cd ../../../..'
alias .5='cd ../../../../..'

alias vim='~/bin/vim'
alias vi='~/bin/vim'
alias vimdiff='vim -d'
alias c='clear'
alias install='sudo apt install'
alias apt-get='sudo apt'
alias p='pwd'
alias ks='ls'
alias sl='ls'
alias LS='ls'
alias amke='make'
alias mkae='make'
alias fhere='find . -name'
alias mkdir='mkdir -pv'

