## get rid of command not found ##
alias cd..='cd ..'
## a quick way to get out of current directory ##
alias vim='/home/selyunin/bin/vim'
alias vi='/home/selyunin/bin/vim'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias .2='cd ../..'
alias .3='cd ../../..'
alias .4='cd ../../../..'
alias .5='cd ../../../../..'

alias c='clear'
alias install='sudo apt-get install'
alias apt-get='sudo apt-get'
alias vimdiff='vim -d'
alias p='pwd'
alias ks='ls'
alias sl='ls'
alias LS='ls'
alias amke='make'
alias mkae='make'
alias fhere='find . -name'
alias mkdir='mkdir -pv'

